dns:
  baseDomain: edge.local

network:
  clusterNetwork:
    - cidr: 10.42.0.0/16
  serviceNetwork:
    - 10.43.0.0/16
  serviceNodePortRange: 30000-32767

node:
  hostnameOverride: rh-edge-node
  nodeIP: ""

apiServer:
  subjectAltNames: []

debugging:
  logLevel: Normal
