FROM registry.access.redhat.com/ubi10/python-312:latest

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY templates/ ./templates/
COPY static/ ./static/

EXPOSE 8888
CMD ["gunicorn", "--bind", "0.0.0.0:8888", "--workers", "1", "--threads", "4", "app:app"]
